version: '3'

services:
    consulserver01:
        build:
            context: ./servers
            dockerfile: Dockerfile
        container_name: consulserver01
        hostname: consulserver01
        ports:
            - 8500:8500
        volumes:
            - ./servers/server01:/etc/consul.d

    consulserver02:
        build:
            context: ./servers
            dockerfile: Dockerfile
        container_name: consulserver02
        hostname: consulserver02
        volumes:
            - ./servers/server02:/etc/consul.d

    consulserver03:
        build:
            context: ./servers
            dockerfile: Dockerfile
        container_name: consulserver03
        hostname: consulserver03
        volumes:
            - ./servers/server03:/etc/consul.d

    consulclient01:
        build:
            context: ./clients
            dockerfile: Dockerfile
        container_name: consulclient01
        hostname: consulclient01
        volumes:
            - ./clients/consul01:/etc/consul.d

    consulclient02:
        build:
            context: ./clients
            dockerfile: Dockerfile
        container_name: consulclient02
        hostname: consulclient02
        volumes:
            - ./clients/consul02:/etc/consul.d
        